{% set name = "hydra-zen" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1b53d74aa1f0baa04fafdac6aba7a94ae40929e7b0a5a5081d8740f74322052d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel >=0.29.0
    - setuptools-scm ==7.0.5
    - pip
  run:
    - python >={{ python_min }}
    - hydra-core >=1.2.0
    - omegaconf >=2.2.1
    - typing-extensions >=4.1.0,!=4.6.0

test:
  imports:
    - hydra_zen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mit-ll-responsible-ai/hydra-zen
  summary: Configurable, reproducible, and scalable workflows in Python, via Hydra
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/mit-ll-responsible-ai/hydra-zen
  doc_url: https://mit-ll-responsible-ai.github.io/hydra-zen

extra:
  recipe-maintainers:
    - cameronraysmith
